[2024-12-23T14:21:01.815+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.best_model manual__2024-12-23T14:19:40.925476+00:00 [queued]>
[2024-12-23T14:21:01.830+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.best_model manual__2024-12-23T14:19:40.925476+00:00 [queued]>
[2024-12-23T14:21:01.830+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-12-23T14:21:01.848+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): best_model> on 2024-12-23 14:19:40.925476+00:00
[2024-12-23T14:21:01.858+0000] {standard_task_runner.py:60} INFO - Started process 22727 to run task
[2024-12-23T14:21:01.862+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'best_model', 'manual__2024-12-23T14:19:40.925476+00:00', '--job-id', '419', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmp63t3luml']
[2024-12-23T14:21:01.863+0000] {standard_task_runner.py:88} INFO - Job 419: Subtask best_model
[2024-12-23T14:21:01.881+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T14:21:01.918+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.best_model manual__2024-12-23T14:19:40.925476+00:00 [running]> on host b853fb0270cd
[2024-12-23T14:21:01.999+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T14:19:40.925476+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T14:19:40.925476+00:00'
[2024-12-23T14:21:02.042+0000] {logging_mixin.py:188} INFO - The best Model is Decision Tree Regressor,  -72.45615904903637 
[2024-12-23T14:21:02.043+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract.py", line 234, in best_model_function
    train_and_save_model (DecisionTreeRegressor(random_state = 0), feats, target, "decision_tree_regresor")
  File "/opt/airflow/dags/extract.py", line 208, in train_and_save_model
    os.makedirs(path_to_model)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app/model'
[2024-12-23T14:21:02.046+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=best_model, execution_date=20241223T141940, start_date=20241223T142101, end_date=20241223T142102
[2024-12-23T14:21:02.053+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 419 for task best_model ([Errno 13] Permission denied: '/app/model'; 22727)
[2024-12-23T14:21:02.074+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-23T14:21:02.099+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
