[2024-12-24T11:04:03.504+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: weather_dag.Is_weather_api_ready scheduled__2024-12-24T11:02:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
