[2024-12-23T13:58:51.922+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.best_model manual__2024-12-23T13:57:35.580726+00:00 [queued]>
[2024-12-23T13:58:51.929+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.best_model manual__2024-12-23T13:57:35.580726+00:00 [queued]>
[2024-12-23T13:58:51.930+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-12-23T13:58:51.937+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): best_model> on 2024-12-23 13:57:35.580726+00:00
[2024-12-23T13:58:51.943+0000] {standard_task_runner.py:60} INFO - Started process 18139 to run task
[2024-12-23T13:58:51.945+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'best_model', 'manual__2024-12-23T13:57:35.580726+00:00', '--job-id', '314', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmp_fqzlrk4']
[2024-12-23T13:58:51.945+0000] {standard_task_runner.py:88} INFO - Job 314: Subtask best_model
[2024-12-23T13:58:51.954+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T13:58:51.987+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.best_model manual__2024-12-23T13:57:35.580726+00:00 [running]> on host b853fb0270cd
[2024-12-23T13:58:52.065+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T13:57:35.580726+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T13:57:35.580726+00:00'
[2024-12-23T13:58:52.138+0000] {logging_mixin.py:188} INFO - The best Model is  Random Forest, -65.03073767538172 
[2024-12-23T13:58:52.169+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:578: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

[2024-12-23T13:58:52.170+0000] {logging_mixin.py:188} INFO - RandomForestRegressor(n_estimators=10, oob_score=True, random_state=0) saved at ./app/model.pckl
[2024-12-23T13:58:52.170+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract.py", line 224, in best_model_function
    train_and_save_model( RandomForestRegressor(n_estimators=10, random_state=0, oob_score=True), feats, target)
  File "/opt/airflow/dags/extract.py", line 271, in train_and_save_model
    dump(model, path_to_model)
  File "/home/airflow/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 552, in dump
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './app/model.pckl'
[2024-12-23T13:58:52.173+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=best_model, execution_date=20241223T135735, start_date=20241223T135851, end_date=20241223T135852
[2024-12-23T13:58:52.180+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 314 for task best_model ([Errno 2] No such file or directory: './app/model.pckl'; 18139)
[2024-12-23T13:58:52.197+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-23T13:58:52.209+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
